version: '3.4'

services:
  elastickibaanalogging:
    image: ${DOCKER_REGISTRY-}elastickibaanalogging
    build:
      context: .
      dockerfile: ElasticKibaanaLogging/Dockerfile

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.6.2
    ports:
     - 9200:9200 
    volumes:
     - elasticsearch-data:/ur/share/elasticsearch/data
    environment:
     - xpack.monitoring.enabled=true
     - xpack.watcher.enabled=false
     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
     - discovery.type=single-node
    networks:
     - elastic
  
  kibana:
   container_name: kibana
   image: docker.elastic.co/kibana/kibana:8.6.2
   ports:
    - 5601:5601
   depends_on:
    - elasticsearch
   environment:
    - ElASTICSEARCH_URL=http://localhost:9200
   networks:
    - elastic

networks:
  elastic:
   driver: bridge

volumes:
  elasticsearch-data:
